refactor TKBLContactsLoader;
talkable/ios-sdk pull request #11
Opened 2020-11-26 19:16 UTC by kostilal

add topViewController snipet;

## Related Stories

[![](http://proxies.talkable.com/talkable/PR-14360)](https://talkable.atlassian.net/browse/PR-14360)

2020-11-26 21:37 UTC, zhuravel commented on Talkable/TKBLContactsLoader.h
> +- (void)loadContactsWithComplitionHandler:(void(^)(NSArray* contacts))complitionHandler;
```suggestion
- (void)loadContactsWithCompletionHandler:(void(^)(NSArray* contacts))completionHandler;
```

2020-11-26 21:37 UTC, zhuravel commented on Talkable/TKBLContactsLoader.m
> +    [self requestForAccessWithComplition:^(BOOL granted) {
```suggestion
- (void)loadContactsWithCompletionHandler:(void(^)(NSArray* contacts))completionHandler {
    [self requestForAccessWithCompletion:^(BOOL granted) {
```

2020-11-26 21:37 UTC, zhuravel commented on Talkable/TKBLContactsLoader.m
>                  complitionHandler(contacts);
```suggestion
                completionHandler(contacts);
```

2020-11-26 21:37 UTC, zhuravel commented on Talkable/TKBLContactsLoader.m
> +    NSString *message = NSLocalizedString(@"This app requires access to your contacts to function properly. Please visit to the Privacy section in the Settings app.", nil);
```suggestion
    NSString *message = NSLocalizedString(@"This app requires access to your contacts to function properly. Please visit the Privacy section in the Settings app.", nil);
```

2020-11-26 21:37 UTC, zhuravel commented on Talkable/TKBLContactsLoader.m
> +- (void)requestForAccessWithComplition:(void(^)(BOOL granted))complitionHandler {
```suggestion
- (void)requestForAccessWithCompletion:(void(^)(BOOL granted))completionHandler {
```

2020-11-26 21:37 UTC, zhuravel commented on Talkable/TKBLContactsLoader.m
> +            complitionHandler(YES);
```suggestion
            completionHandler(YES);
```

2020-11-26 21:37 UTC, zhuravel commented on Talkable/TKBLContactsLoader.m
> +                complitionHandler(granted);
```suggestion
                completionHandler(granted);
```

2020-11-26 21:37 UTC, zhuravel commented on Talkable/TKBLOfferTarget.m
> +    [[TKBLContactsLoader new] loadContactsWithComplitionHandler:^(NSArray *contacts) {
```suggestion
    [[TKBLContactsLoader new] loadContactsWithCompletionHandler:^(NSArray *contacts) {
```

2020-11-26 21:37 UTC, zhuravel commented on Talkable/TKBLContactsLoader.m
> +                fullName = [NSString stringWithFormat:@"%@ %@",firstName, lastName];
```suggestion
                fullName = [NSString stringWithFormat:@"%@ %@", firstName, lastName];
```

2020-11-29 17:50 UTC, zhuravel commented on Talkable/TKBLContactsLoader.h
> +- (void)loadContactsWithcompletionHandler:(void(^)(NSArray* contacts))completionHandler;
```suggestion
- (void)loadContactsWithCompletionHandler:(void(^)(NSArray* contacts))completionHandler;
```

2020-11-29 17:50 UTC, zhuravel commented on Talkable/TKBLContactsLoader.m
> +    [self requestForAccessWithcompletion:^(BOOL granted) {
```suggestion
- (void)loadContactsWithCompletionHandler:(void(^)(NSArray* contacts))completionHandler {
    [self requestForAccessWithCompletion:^(BOOL granted) {
```

2020-11-29 17:50 UTC, zhuravel commented on Talkable/TKBLContactsLoader.m
> +- (void)requestForAccessWithcompletion:(void(^)(BOOL granted))completionHandler {
```suggestion
- (void)requestForAccessWithCompletion:(void(^)(BOOL granted))completionHandler {
```

2020-11-29 17:50 UTC, zhuravel commented on Talkable/TKBLOfferTarget.m
> +    [[TKBLContactsLoader new] loadContactsWithcompletionHandler:^(NSArray *contacts) {
```suggestion
    [[TKBLContactsLoader new] loadContactsWithCompletionHandler:^(NSArray *contacts) {
```

2020-12-03 15:05 UTC, dgtv requested changes

2020-12-03 15:05 UTC, dgtv commented on Talkable/TKBLHelper.m
> +    UIViewController *topController = [UIApplication sharedApplication].keyWindow.rootViewController;
In your previous PR I see `topController` could be `null` so looks like you should handle this case:
https://github.com/talkable/talkable-ios-sdk/pull/32/files#diff-875122cdd758244c2ab3c1a9892d8194ea50fbf438ff43aec13a17c50847de8eR45

2020-12-03 15:05 UTC, dgtv commented on Talkable/TKBLContactsLoader.m
> +            ;
What is this?

2020-12-03 15:05 UTC, dgtv commented on Talkable/TKBLContactsLoader.m
> +                                  TKBLContactFullNameKey: fullName ? fullName  : [NSNull null],
Isn't `fullName` always present in current implementation: it equals `[NSString stringWithFormat:@"%@", nil];` if both `firstName` & `lastName ` eq `nil`

2020-12-04 09:07 UTC, kostilal commented on Talkable/TKBLHelper.m
> +    UIViewController *topController = [UIApplication sharedApplication].keyWindow.rootViewController;
It's a difference between Objective-c and swift. In Objective-c you can send message to nil object. And nothing will happens. But in Swift you can't, so you need check for nil object. Here is more information about Objective - c runtime.

[Sending Messages to nil](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ObjectiveC/Chapters/ocObjectsClasses.html )

2020-12-04 09:11 UTC, kostilal commented on Talkable/TKBLContactsLoader.m
> +                                  TKBLContactFullNameKey: fullName ? fullName  : [NSNull null],
You is right, I'l fix it.

2020-12-07 13:54 UTC, dgtv approved these changes

2020-12-09 13:28 UTC, zhuravel approved these changes

2020-12-09 13:48 UTC, merged